services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tests
  

  mongo:
    container_name: mongo
    image: mongo:5.0.6-focal
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./scripts/rs-init.sh:/scripts/rs-init.sh
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]