services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=secret
  

  mongo:
    container_name: mongo
    image: mongo:5.0.6-focal
    ports:
      - "27017:27017"
