site_name: Winter Documentation
site_url: "https://adriangs1996.github.io/winter"

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - User Guide: 
    - Installation: user-guide/installation.md

repo_url: https://github.com/adriangs1996/winter
repo_name: adriangs1996/winter

extra_css:
  - stylesheets/extra.css
  - stylesheets/custom.css
  - stylesheets/termynal.css

extra_javascript:
- js/termy.js
- js/custom.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list

theme:
  name: material
  features:
    - header.autohide
    - ontent.code.annotate
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
        accent: teal
        primary: deep purple
    - scheme: slate 
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
        accent: teal
        primary: deep purple
  highlightjs: false