[tool.poetry]
name = "wintry"
version = "0.1.1-alpha.0"
description = "A Web Framework for you, the developer, in a clean way, a cool way"
authors = ["adriangs1996 <adriangonzalezsanchez1996@gmail.com>"]
license = "MIT"
readme="README.md"
keywords=[
    "orm", 
    "web-framework", 
    "api-rest", 
    "repository", 
    "wintry", 
]

repository="https://github.com/adriangs1996/wintry"
homepage="https://adriangs1996.github.io/wintry"

[tool.poetry.dependencies]
python = "^3.10"
motor = "^2.5.1"
SQLAlchemy = "^1.4.35"
asyncpg = {version = "^0.25.0", optional = true}
dataclass-wizard = "^0.22.0"
pydantic = "^1.9.0"
fastapi = "^0.75.2"
Inject = "^4.3.1"
uvicorn = {extras = ["standard"], version = "^0.17.6"}
aioredis = {version = "^2.0.1", optional = true }
pika = {version = "^1.2.1", optional = true}
aio-pika = "^7.2.0"

[tool.poetry.extras]
postgres = ["asyncpg"]
redis = ["aioredis"]
amqp = ["pika"]

[tool.poetry.dev-dependencies]
black = "^22.3.0"
pytest = "^7.1.1"
pytest-asyncio = "^0.18.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 90
