[tool.poetry]
name = "winter"
version = "0.1.0"
description = "Python web development's future rely on magic, and magic is coming (like winter in GOT)"
authors = ["adriangs1996 <adriangonzalezsanchez1996@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
motor = "^2.5.1"
SQLAlchemy = {version = "^1.4.35", optional = true}
asyncpg = {version = "^0.25.0", optional = true}
dataclass-wizard = "^0.22.0"
pydantic = "^1.9.0"
pyee = "^9.0.4"
fastapi = "^0.75.2"
Inject = "^4.3.1"

[tool.poetry.extras]
postgres = ["SQLAlchemy", "asyncpg"]

[tool.poetry.dev-dependencies]
black = "^22.3.0"
pytest = "^7.1.1"
pytest-asyncio = "^0.18.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 110
